<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [38]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
import numpy as np

def matrix_mul(A, B):
    # write your code
    num_rows_A=len(A)
    num_cols_A=len(A[0])
    num_rows_B=len(B)
    num_cols_B=len(B[0])
    if num_cols_A!=num_rows_B:
      print("Multiplication not possible")
      return 
    else:
      mat = []
      for i in range (num_rows_A):
        rowList = []
        for j in range (num_cols_B):
                rowList.append(0)
        mat.append(rowList)
     
      for i in range(num_rows_A):
        for j in range(num_cols_B):
          for k in range(num_rows_B):
            mat[i][j]+= A[i][k]*B[k][j]
    return mat

A = [[1,2,5],
     [3,4,9],
     [5,6,1]]
B = [[1 ,2 ,3 ,4 ,5],
     [5 ,6 ,7 ,8 ,9],
     [5, 9, 1, 2, 9]]
r=matrix_mul(A, B)

for q in r:
  print(q)

[36, 59, 22, 30, 68]
[68, 111, 46, 62, 132]
[40, 55, 58, 70, 88]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [39]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #print(sum(A))
    A_new=[]
    A_new_1=[]
    sum=0
    for i in range(len(A)):
      sum+=A[i]
    
    for j in range(len(A)):
      x=A[j]/sum
      A_new.append(x)

    for k in range(len(A)):
      A_new_1.insert(k,A_new[k])
      if k==0:
         A_new_1[k]=A_new[k]
      else:
         A_new_1[k]+=A_new_1[k-1]
     
    r=uniform(0,1)
    if r<=A_new_1[0]:
        return A[0]
    elif r>A_new_1[0] and r<=A_new_1[1]:
        return A[1]
    elif r>A_new_1[1] and r<=A_new_1[2]:
        return A[2]
    elif r>A_new_1[2] and r<=A_new_1[3]:
        return A[3]
    elif r>A_new_1[3] and r<=A_new_1[4]:
        return A[4]
    elif r>A_new_1[4] and r<=A_new_1[5]:
        return A[5]
    elif r>A_new_1[5] and r<=A_new_1[6]:
        return A[6]
    elif r>A_new_1[6] and r<=A_new_1[7]:
        return A[7]
    elif r>A_new_1[7] and r<=A_new_1[8]:
        return A[8]
    elif r>A_new_1[8] and r<=A_new_1[9]:
        return A[9]
     
      
    

def sampling_based_on_magnitued():
    A = [0 ,5 ,27 ,6 ,13 ,28 ,100 ,45 ,10 ,79]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

79
28
45
100
45
100
79
79
100
6
100
100
10
79
13
79
100
100
10
100
79
28
100
28
79
79
100
45
100
13
13
10
100
79
100
100
45
100
45
100
45
100
79
27
100
100
79
79
45
45
100
27
100
45
45
13
79
79
79
45
10
5
79
79
45
79
79
100
100
28
27
79
45
45
100
79
100
28
28
5
13
100
100
79
79
28
79
79
100
28
100
28
10
100
100
100
27
79
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    s=re.sub('\D',"",String)
    s=re.sub('\d','#',s)
    
    return(s) # modified string which is after replacing the # with digits
String="23456#$%^!@"
replace_digits(String)

'#####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
import math

def display_dash_board(students, marks):
    # write code for computing top top 5 students
    #top_5_students = # compute this
    # write code for computing top least 5 students
    index=[]
    students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
    index=sorted(marks)
    zipped=list(zip(students,marks))
    zip_sorted=sorted(zipped,key=lambda t:t[1],reverse=True)

  
    zip_sorted_1=sorted(zipped,key=lambda t:t[1])

  
    students_between_25_and_75_percentile= zip_sorted[math.ceil(0.25*len(zipped)): math.floor(0.75*len(zipped))]

   

    return zip_sorted[:5], zip_sorted_1[:5], students_between_25_and_75_percentile
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students, marks)
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75 )

[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
[('student5', 48), ('student7', 47), ('student1', 45), ('student6', 43)]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [12]:
import math
import numpy as np

distance=[]
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    for a,b in S:
      num= a*P[0] + b*P[1]
      den= (math.sqrt(a**2 + b**2))*(math.sqrt(P[0]**2 + P[1]**2))
      dis=math.acos(num/den)
      distance.append(dis)
    
    zipp=list(zip(S,distance))
    zipped=sorted(zipp,key=lambda t:t[1])[0:5]

    return zipped

S= [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
P= (3,-4)
s_d=closest_points_to_p(S, P)
for i,j in s_d:
  print(i) #print the returned values (only points)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [41]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    list1=[]
    list2=[]
    # your code
    
    for element in red:
      equation=line.replace('x','*'+str(element[0]))
      equation=equation.replace('y','*'+str(element[1]))
      result1=eval(equation)
      list1.append(result1)
    for element in blue:
      equation=line.replace('x','*'+str(element[0]))
      equation=equation.replace('y','*'+str(element[1]))
      result1=eval(equation)
      list2.append(result1)
    for i in range(len(list1)):
      if list1[i]>0 and list2[i]<0:
        return 'yes'
      else:
        return "no"
    

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

yes
no
no
yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [96]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

def curve_smoothing(S):
    a=S.split(",")
    count=0
    middle=0
    
    # blanks on left
    for i in range(len(a)):
        if a[i] == '_':
            count = count + 1  
        else:
            for j in range(i + 1):
       
                a[j] = ((float(a[i]) / (count + 1)))
            middle= i
            middle_store_value = float(a[i])
           
            break
   
    # blanks in the middle
   
    flag = 0
    for k in range(middle + 1, len(a)):
      if a[k] != '_':
            denominator = (k + 1 - middle)
            flag = k
            break
    
    for p in range(middle,flag+1):
       a[p] = ((middle_store_value+float(a[flag])) / (denominator)) 
    val= a[flag]
     
  
    ##blanks on right

    for q in range(flag,len(a)):
      a[q]= float(val) /(len(a)-flag)
    return a
S= "_,_,30,_,_,_,50,_,_"
print(curve_smoothing(S))

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions
  
  for j in range(1,6):
    cnt1=0
    cnt2=0
    cnt3=0
    len_s1=0
    len_s2=0
    len_s3=0
    for i in range(len(A)):
      if A[i][1]=='S1':
        len_s1+=1
      elif A[i][1]=='S2':
        len_s2+=1
      else:
        len_s3+=1
    for i in range(len(A)):
      if A[i][0]=='F'+str(j) and A[i][1]=='S1':
        cnt1+=1
      
      elif A[i][0]=='F'+str(j) and A[i][1]=='S2':
        cnt2+=1
      
      elif A[i][0]=='F'+str(j) and A[i][1]=='S3':
        cnt3+=1
      
    prob1=cnt1/len_s1
    prob2=cnt2/len_s2
    prob3=cnt3/len_s3
    print("conditional probs when F=F"+str(j)+"and S= S1 or S2 or S3")
    print("conditional probs when F=F"+str(j)+" and S= S1:",prob1)
    print("conditional probs when F=F"+str(j)+" and S= S2:",prob2)
    print("conditional probs when F=F"+str(j)+" and S= S3:",prob3)
    print("#"*20)

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

conditional probs when F=F1and S= S1 or S2 or S3
conditional probs when F=F1 and S= S1: 0.25
conditional probs when F=F1 and S= S2: 0.3333333333333333
conditional probs when F=F1 and S= S3: 0.0
####################
conditional probs when F=F2and S= S1 or S2 or S3
conditional probs when F=F2 and S= S1: 0.25
conditional probs when F=F2 and S= S2: 0.3333333333333333
conditional probs when F=F2 and S= S3: 0.3333333333333333
####################
conditional probs when F=F3and S= S1 or S2 or S3
conditional probs when F=F3 and S= S1: 0.0
conditional probs when F=F3 and S= S2: 0.3333333333333333
conditional probs when F=F3 and S= S3: 0.3333333333333333
####################
conditional probs when F=F4and S= S1 or S2 or S3
conditional probs when F=F4 and S= S1: 0.25
conditional probs when F=F4 and S= S2: 0.0
conditional probs when F=F4 and S= S3: 0.3333333333333333
####################
conditional probs when F=F5and S= S1 or S2 or S3
conditional probs when F=F5 and S= S1: 0.25
conditional probs 

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    words_s1=S1.split()
    words_s2=S2.split()
    list=[]
    list1=[]
    list2=[]
    for i in words_s1:
      if i in words_s2:
        list.append(i)
        a=len(list)
   
    for i in words_s1:
      if i in words_s1 and i not in words_s2:
        list1.append(i)
        b=(list1)
    for i in words_s2:
      if i in words_s2 and i not in words_s1:
        list2.append(i)
        c=(list2)

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c=string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import numpy as np
# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    sum=0
    for i in range(len(A)):
      a= A[i][0]*np.log10(A[i][1]) + (1-A[i][0])*np.log10(1-A[i][1])
      sum+=a
    loss= (-1*sum)/(len(A))
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
